// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDQYlEGYZDnQh-0EV3iNVlU5YOvD0-v2Q',
    appId: '1:728614145047:web:eff2c4cc79c546e90c2052',
    messagingSenderId: '728614145047',
    projectId: 'graket-academy',
    authDomain: 'graket-academy.firebaseapp.com',
    databaseURL: 'https://graket-academy-default-rtdb.firebaseio.com',
    storageBucket: 'graket-academy.appspot.com',
    measurementId: 'G-LSR1XC9NFK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTb18M2it4ZucxTAmY3fmLbGzxjcWOOiU',
    appId: '1:728614145047:android:fae62b3259b9574f0c2052',
    messagingSenderId: '728614145047',
    projectId: 'graket-academy',
    databaseURL: 'https://graket-academy-default-rtdb.firebaseio.com',
    storageBucket: 'graket-academy.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBbKovrbuYD12G5OpRQhkZ_y7JBMzhwGR4',
    appId: '1:728614145047:ios:a0695c59b10874520c2052',
    messagingSenderId: '728614145047',
    projectId: 'graket-academy',
    databaseURL: 'https://graket-academy-default-rtdb.firebaseio.com',
    storageBucket: 'graket-academy.appspot.com',
    iosClientId:
        '728614145047-ofv911o4jii6860lge9qv4e052snqqat.apps.googleusercontent.com',
    iosBundleId: 'com.yssoftware.graketAcademy',
  );
}
